enabled: True
python: |
  def while_try_except_finally():
    res = []
    n = 5
    while n > 0:
      n -= 1
      if n == 2:
        continue
      res.append(n)
    
    return res == [4, 3, 1, 0]