enabled: True
python: |
  def for_try_break():
    res = []
    arr = [1, 2, 4, 0, 8]
    
    for num in arr:
      try:
        result = 16 // num
        res.append(result)
      except ZeroDivisionError:
        print("Sorry ! You are dividing by zero ")
        break
    
    return res == [16, 8, 4]